version: "2"
linters:
  enable:
    - copyloopvar # Checks for loop variable copies in Go 1.22+
    - depguard # Checks for dependencies that should not be (re)introduced. See "settings" for further details.
    - dupword # Checks for duplicate words in the source code
    - gosec
    - revive
    - misspell
    - nolintlint
    - unconvert
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/opencontainers/runc
              desc: We don't want to depend on runc (libcontainer), unless there is no other option; see https://github.com/opencontainers/runc/issues/3028.
    forbidigo:
      forbid:
        - pkg: ^regexp$
          msg: Use internal/lazyregexp.New instead.
    gosec:
      # The following issues surfaced when `gosec` linter
      # was enabled. They are temporarily excluded to unblock
      # the existing workflow, but still to be addressed by
      # future works.
      excludes:
        - G103 # Audit the use of unsafe block
        - G104 # Errors unhandled; (TODO: reduce unhandled errors, or explicitly ignore)
        - G115 # integer overflow conversion; (TODO: verify these: https://github.com/moby/moby/issues/48358)
        - G204 # Subprocess launched with variable; too many false positives.
        - G301 # Expect directory permissions to be 0750 or less (also EXC0009); too restrictive
        - G302 # Expect file permissions to be 0600 or less (also EXC0009); too restrictive
        - G304 # Potential file inclusion via variable.
        - G305 # File traversal when extracting zip/tar archive
        - G306 # Expect WriteFile permissions to be 0600 or less (too restrictive; also flags "0o644" permissions)
        - G402 # Look for bad TLS connection settings
        - G404 # Insecure random number source (rand)
    staticcheck:
      checks:
        - all
        - -QF1008 # Omit embedded fields from selector expression; https://staticcheck.dev/docs/checks/#QF1008
        - -ST1000 # Incorrect or missing package comment; https://staticcheck.dev/docs/checks/#ST1000
        - -ST1020 # type should start with type's name; https://staticcheck.dev/docs/checks/#ST1021
        - -ST1021 # variable or constant should start with variable's name; https://staticcheck.dev/docs/checks/#ST1022
    revive:
      rules:
        - name: package-comments
          severity: warning
          disabled: true
          exclude: [ "" ]
    nolintlint:
      allow-unused: true
  exclusions:
    generated: lax
    rules:
      - path: cmd[\\/]containerd[\\/]builtins[\\/]
        text: 'blank-imports:'
      - path: contrib[\\/]fuzz[\\/]
        text: 'exported: func name will be used as fuzz.Fuzz'
      - path: archive[\\/]tarheader[\\/]
        # conversion is necessary on Linux, unnecessary on macOS
        text: unnecessary conversion
      - path: integration[\\/]client
        text: 'dot-imports:'
      - linters:
          - revive
        text: if-return
      - linters:
          - revive
        text: empty-block
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: unreachable-code
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - forbidigo
        text: 'use of `regexp.MustCompile` forbidden'
        path: _test\.go
    paths:
      - api
      - cluster
      - docs
      - docs/man
      - releases
      - test
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
    paths:
      - api
      - cluster
      - docs
      - docs/man
      - releases
      - test